/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(multiplyconf.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(1e9d4d66b2edb5ed8c712c2ff15280a6)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <oot/multiplyconf.h>
// pydoc.h is automatically generated in the build directory
#include <multiplyconf_pydoc.h>

void bind_multiplyconf(py::module& m)
{

    using multiplyconf    = gr::oot::multiplyconf;


    py::class_<multiplyconf, gr::block, gr::basic_block,
        std::shared_ptr<multiplyconf>>(m, "multiplyconf", D(multiplyconf))

        .def(py::init(&multiplyconf::make),
           D(multiplyconf,make)
        )
        



        ;




}








