/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(multiplyconf2.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(f033c6572c389515704fe3c3e150c052)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/oot/multiplyconf2.h>
// pydoc.h is automatically generated in the build directory
#include <multiplyconf2_pydoc.h>

void bind_multiplyconf2(py::module& m)
{

    using multiplyconf2    = ::gr::oot::multiplyconf2;


    py::class_<multiplyconf2, gr::block, gr::basic_block,
        std::shared_ptr<multiplyconf2>>(m, "multiplyconf2", D(multiplyconf2))

        .def(py::init(&multiplyconf2::make),
           py::arg("m1"),
           py::arg("m2"),
           D(multiplyconf2,make)
        )
        



        ;




}








